---
- name: X1 Carbon copy Xorg configs
  become: true
  copy:
    src: xorg.conf.d/
    dest: /etc/X11/xorg.conf.d/
  tags:
    - x1-x

- name: X1 Carbon copy /etc/default configs
  become: true
  copy:
    src: default/
    dest: /etc/default/
  tags:
    - x1-x
