---
- name: Install ninja
  when: ansible_pkg_mgr != 'homebrew'
  become: true
  package:
    state: present
    name:
      - ninja-build
  tags:
    - lua

- name: Install ninja (brew)
  when: ansible_pkg_mgr == 'homebrew'
  become: false
  package:
    state: present
    name:
      - ninja
  tags:
    - lua

- name: Clone lua-language-server
  git:
    repo: https://github.com/sumneko/lua-language-server
    dest: ~/.local/lua-language-server
    recursive: true
    depth: 1
    update: true
  tags:
    - lua
    - luarepo

- name: Building luamake (Linux)
  when: ansible_os_family == 'Debian'
  command: ninja -f ./compile/ninja/linux.ninja
  args:
    chdir: ~/.local/lua-language-server/3rd/luamake
    creates: build/linux/bin/luamake
  tags:
    - lua

- name: Building luamake (Darwin)
  when: ansible_os_family == 'Darwin'
  command: ninja -f ./compile/ninja/macos.ninja
  args:
    chdir: ~/.local/lua-language-server/3rd/luamake
    creates: build/macos/bin/luamake
  tags:
    - lua

- name: Building lua-language-server
  command: ./3rd/luamake/luamake rebuild
  args:
    chdir: ~/.local/lua-language-server/
    creates: ~/.local/bin/Linux/lua-language-server
  tags:
    - lua


      #- name: Install luacheck
      #  command: luarocks --local install luacheck
      #  args:
      #    creates: ~/.luarocks/bin/luacheck
      #  tags:
      #    - lua
